name: Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  pre-release:
    strategy:
      matrix:
        os: [  ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install Dependencies on ${{ runner.os }}
        if: ${{ runner.os == 'ubuntu-latest' }}
        run: |
          wget https://github.com/tinygo-org/tinygo/releases/download/v0.23.0/tinygo_0.23.0_amd64.deb
          sudo dpkg -i tinygo_0.23.0_amd64.deb
          sudo apt update && sudo apt install -y upx

      - name: Install Dependencies on ${{ runner.os }}
        if: ${{ runner.os == 'macos-latest' }}
        run: |
          brew tap tinygo-org/tools
          brew install golang tinygo upx

      - name: Build
        run: |
          make
          mv out/luckypg out/luckypg-${{ runner.os }}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            out/*
